spring:
  application:
    name:
      trainee-app-with-data-jpa
  datasource:
    url: jdbc:sqlserver://${RDS_HOSTNAME:localhost}:${RDS_PORT:1433};databaseName=${RDS_DB_NAME:ust_aws_db};encrypt=true;trustServerCertificate=true
    username: ${RDS_USERNAME:admin}
    password: ${RDS_PASSWORD:Sqlserver-123}
#    password: ${DB_PASSWORD:MyStrongPass123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port:
    5000
